// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsbcfepjnblsaifsolfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzYmNmZXBqbmJsc2FpZnNvbGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzODQzMjcsImV4cCI6MjA2Mzk2MDMyN30.onPfVCPjIZHiJ9k5gBON3i1uVWNFtmpqDli804s1TW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);